<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FunicularSwitch.Generators" Version="4.6.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-77" />
      <PackageReference Include="TreeSitter.DotNet" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="grammar.json" />
      <EmbeddedResource Include="grammar.json" />
      <None Remove="node-types.json" />
      <EmbeddedResource Include="node-types.json" />
    </ItemGroup>

</Project>
